version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema_db_jwt
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/cinema_db.sql:/cinema_db.sql